### ISSUE TITLE
use body-parser middleware

### ISSUE THREAD

**Issue by davehorton** [davehorton/cautious-enigma#2]
I think we should have:
```
const bodyParser = require('body-parser');
..
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```
for json parsing, somewhere around [here](https://github.com/davehorton/cautious-enigma/blob/cf55b0b44f3f06d65ff4378bb506de39762ee33f/server.js#L8), no ?

**Comment by jamesnuanez** [comment]
Express v4.16.0 includes these as [express.urlencoded([options])](http://expressjs.com/en/4x/api.html#express.urlencoded) and [express.json([options])](http://expressjs.com/en/4x/api.html#express.json) (it's still `body-parser` under the hood, though).

**Comment by davehorton** [comment]
ah, thx
